apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: todo-app-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: todo_app_alerts
    interval: 30s
    rules:
    - alert: TodoAppDown
      expr: up{job="todo-app-svc"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Todo application is down"
        description: "Todo app has been down for more than 2 minutes"
        
    - alert: HighErrorRate
      expr: |
        (sum(rate(flask_http_request_total{status=~"5.."}[5m])) / 
        sum(rate(flask_http_request_total[5m]))) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 5%"
        
    - alert: DatabaseConnectionFailed
      expr: db_connection_health == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Database connection is failing for your todo app"
        description: "Cannot connect to database"