services:
  db:
    image: mysql:8.0
    environment:
         MYSQL_DATABASE: todo_db
         MYSQL_USER: todo_user
         MYSQL_PASSWORD: todo_pass
         MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u todo_user -ptodo_pass" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  web:
    build:
      context: ./app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
      MYSQL_DATABASE: todo_db 
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
volumes:
  mysqldata: