apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: perischepkemoi/flask-todo-app:v1.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-configs
              key: db_name
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configs
              key: db_host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_password
