name: CI/CD Pipeline to deploy to EKS

on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

jobs:     
  build-and-deploy:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 

      - name: Test the pipeline
        run: echo Hello, world!