name: Set up infrastructure with Terraform
permissions:
  contents: write
on:
  push:
    branches: ["main"]
    paths:
      - 'terraform/**'
      - '!terraform/README.md'    
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  setup-infra-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3 
          terraform_wrapper: false

      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform -chdir=terraform init  

      - name: Terraform Plan
        run: terraform -chdir=terraform plan  
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Apply Terraform configuration
        run: terraform -chdir=terraform apply -auto-approve  
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      
      - name: Get RDS endpoint from Terraform
        id: tf_output
        run: |
          ENDPOINT=$(terraform -chdir=terraform output -raw rds_host)
          echo "rds_host=$ENDPOINT" >> $GITHUB_OUTPUT
          echo "RDS Endpoint: $ENDPOINT"
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Update ConfigMap with RDS endpoint
        run: |
          sed -i "s|db_host:.*|db_host: ${{ steps.tf_output.outputs.rds_host }}|g" k8s/configmap.yaml
          cat k8s/configmap.yaml   

      - name: Commit and push updated ConfigMap
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git add k8s/configmap.yaml
            git diff --staged --quiet || git commit -m "Update RDS endpoint in ConfigMap [skip ci]"
            git push


      



