name: Set up infrastructure with Terraform

on:
  push:
    branches: ["main"]
    paths:
      - 'terraform/**'
      - '!terraform/README.md'    

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3 

      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init terraform/

      - name: Terraform Plan
        run: terraform plan terraform/

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve terraform/
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
